import java.util.Random;
import java.util.Scanner;

public class Lottery {
	private int lotteryNumber[] = new int[5];
	private int userLotteryNumber[] = new int[5];
	private Scanner input = new Scanner(System.in);
	
	//Constructor
	public Lottery()
	{
		//Random number generator
		Random random = new Random();
		//generate random number and add to lotterynumber
		for(int i=0;i<5;i++)
			lotteryNumber[i] = Math.abs(random.nextInt())%9;;
	}
	
	//user lottery number
	public void userLotteryNumber()
	{
		for(int i=0;i<5;i++)
		{
			int number = input.nextInt();
			try{
				//check the input number, if number is not in range throw exception
				if(number>=0 && number <=9)
					this.userLotteryNumber[i] =number;
				else
					throw new OutOfRangeException("Number not in Range(0-9)");
			}
			catch(OutOfRangeException e){
				System.out.println("ERROR: "+e);
				i--;
			}
			
		}
	}
	
	//method to compare digits of lottery tickets
	public int compare()
	{
		int match=0;
		for(int i=0;i<lotteryNumber.length;i++)
		{
			if(userLotteryNumber[i]==lotteryNumber[i])
				match++;
		}
		return match;	
	}
	
	//lottery number generated by system
	public void LotteryNumber()
	{
		for(int i: lotteryNumber)
			System.out.println(i);
	}
	
	//inner class for handling user defined Exception for checking range of number
	@SuppressWarnings("serial")
	class OutOfRangeException extends Exception {
		//constructor to send message to parent 
		OutOfRangeException(String s)
		{super(s);}
	}
}
